BUILDDIR ?= out

SIG20 := soc_lk_12_24.lua soc_lk_12_12.lua soc_lk_12_6.lua soc_lk_12_4.lua soc_lk_12_3.lua soc_lk_12_2.lua soc_lk_12_1.lua
SIG20 += soc_lk_6_6.lua soc_lk_6_3.lua soc_lk_6_2.lua soc_lk_6_1.lua 
SIG20 += soc_lk_4_8.lua soc_lk_4_4.lua soc_lk_4_2.lua soc_lk_4_1.lua 
SIG20 += soc_convgenTaps_8_1.lua soc_convgenTaps_8_2.lua soc_convgenTaps_8_4.lua  soc_convgenTaps_8_8.lua soc_convgenTaps_8_16.lua soc_convgenTaps_8_32.lua soc_convgenTaps_8_64.lua
SIG20 += soc_stereo_tiny_4_4.lua soc_stereo_tiny_4_1.lua soc_stereo_tiny_4_2.lua soc_stereo_tiny_4_8.lua soc_stereo_full_64_64.lua soc_stereo_full_64_32.lua soc_stereo_full_64_16.lua soc_stereo_full_64_8.lua soc_stereo_full_64_4.lua
SIG20 += soc_sift_1_2.lua soc_sift_1_2_autofifo.lua soc_sift_1_8.lua soc_sift_1_8_autofifo.lua soc_sift_1_16.lua soc_sift_1_16_autofifo.lua
SIG20 += soc_sift_4_64.lua soc_sift_4_64_1080p.lua soc_sift_4_128.lua soc_sift_4_128_1080p.lua soc_sift_4_256.lua soc_sift_4_256_1080p.lua
#autofifo
SIG20 += soc_lk_12_24_autofifo.lua soc_lk_12_12_autofifo.lua soc_lk_12_6_autofifo.lua soc_lk_12_4_autofifo.lua soc_lk_12_3_autofifo.lua soc_lk_12_2_autofifo.lua soc_lk_12_1_autofifo.lua
SIG20 += soc_lk_6_6_autofifo.lua soc_lk_6_3_autofifo.lua soc_lk_6_2_autofifo.lua soc_lk_6_1_autofifo.lua 
SIG20 += soc_lk_4_8_autofifo.lua soc_lk_4_4_autofifo.lua soc_lk_4_2_autofifo.lua soc_lk_4_1_autofifo.lua 
SIG20 += soc_convgenTaps_8_1_autofifo.lua soc_convgenTaps_8_2_autofifo.lua soc_convgenTaps_8_4_autofifo.lua  soc_convgenTaps_8_8_autofifo.lua soc_convgenTaps_8_16_autofifo.lua soc_convgenTaps_8_32_autofifo.lua soc_convgenTaps_8_64_autofifo.lua
SIG20 += soc_stereo_tiny_4_4_autofifo.lua soc_stereo_tiny_4_1_autofifo.lua soc_stereo_tiny_4_2_autofifo.lua soc_stereo_tiny_4_8_autofifo.lua soc_stereo_full_64_64_autofifo.lua soc_stereo_full_64_32_autofifo.lua soc_stereo_full_64_16_autofifo.lua soc_stereo_full_64_8_autofifo.lua soc_stereo_full_64_4_autofifo.lua
SIG20 += soc_sift_4_64_autofifo.lua soc_sift_4_64_1080p_autofifo.lua soc_sift_4_128_autofifo.lua soc_sift_4_128_1080p_autofifo.lua soc_sift_4_256_autofifo.lua soc_sift_4_256_1080p_autofifo.lua

SIG20_TODO := $(patsubst %.lua,$(BUILDDIR)/%.zu9vivadoSOC.launch,$(SIG20))
SIG20_TODO += $(patsubst %.lua,$(BUILDDIR)/%.verilatorSOC.launch,$(SIG20))
SIG20_TODO += $(patsubst %.lua,$(BUILDDIR)/%.v.launch,$(SIG20))
SIG20_TODO += $(patsubst %.lua,$(BUILDDIR)/%.zu9vivadoSOC.stats2020.launch,$(SIG20))

# CPP version
SIG20CPP = out/soc_convgenTaps_8_1.lua out/soc_convgenTaps_8_2.lua out/soc_convgenTaps_8_4.lua  out/soc_convgenTaps_8_8.lua out/soc_convgenTaps_8_16.lua out/soc_convgenTaps_8_32.lua out/soc_convgenTaps_8_64.lua
SIG20CPP += out/soc_convgenTaps_8_1_autofifo.lua out/soc_convgenTaps_8_2_autofifo.lua out/soc_convgenTaps_8_4_autofifo.lua  out/soc_convgenTaps_8_8_autofifo.lua out/soc_convgenTaps_8_16_autofifo.lua out/soc_convgenTaps_8_32_autofifo.lua out/soc_convgenTaps_8_64_autofifo.lua
SIG20CPP += out/soc_sift_4_64_1080p.lua out/soc_sift_4_128_1080p.lua out/soc_sift_4_256_1080p.lua
SIG20CPP += out/soc_sift_4_64_1080p_autofifo.lua out/soc_sift_4_128_1080p_autofifo.lua out/soc_sift_4_256_1080p_autofifo.lua
SIG20CPP += out/soc_stereo_full_64_64.lua out/soc_stereo_full_64_32.lua out/soc_stereo_full_64_16.lua out/soc_stereo_full_64_8.lua out/soc_stereo_full_64_4.lua
SIG20CPP += out/soc_stereo_full_64_64_autofifo.lua out/soc_stereo_full_64_32_autofifo.lua out/soc_stereo_full_64_16_autofifo.lua out/soc_stereo_full_64_8_autofifo.lua out/soc_stereo_full_64_4_autofifo.lua
SIG20CPP += out/soc_lk_12_24.lua out/soc_lk_12_12.lua out/soc_lk_12_6.lua out/soc_lk_12_4.lua out/soc_lk_12_3.lua out/soc_lk_12_2.lua out/soc_lk_12_1.lua
SIG20CPP += out/soc_lk_12_24_autofifo.lua out/soc_lk_12_12_autofifo.lua out/soc_lk_12_6_autofifo.lua out/soc_lk_12_4_autofifo.lua out/soc_lk_12_3_autofifo.lua out/soc_lk_12_2_autofifo.lua out/soc_lk_12_1_autofifo.lua

SIG20CPP_TODO := $(patsubst out/%.lua,$(BUILDDIR)/%.zu9vivadoSOC.launch,$(SIG20CPP))
SIG20CPP_TODO += $(patsubst out/%.lua,$(BUILDDIR)/%.verilatorSOC.launch,$(SIG20CPP))
SIG20CPP_TODO += $(patsubst out/%.lua,$(BUILDDIR)/%.v.launch,$(SIG20CPP))
SIG20CPP_TODO += $(patsubst out/%.lua,$(BUILDDIR)/%.zu9vivadoSOC.stats2020.launch,$(SIG20CPP))

SIG16 := convpadcrop_wide_handshake_8_8_1080p.lua convpadcrop_wide_handshake_8_4_1080p.lua convpadcrop_wide_handshake_8_2_1080p.lua conv_tr_handshake_8_1_1080p.lua conv_tr_handshake_8_2_1080p.lua conv_tr_handshake_8_4_1080p.lua conv_tr_handshake_8_8_1080p.lua
SIG16 += stereo_wide_handshake_full.lua stereo_tr_full_4.lua stereo_tr_full_8.lua stereo_tr_full_16.lua stereo_wide_handshake_tiny.lua stereo_tr_tiny_1.lua stereo_tr_tiny_2.lua stereo_tr_tiny_4.lua
SIG16 += lk_wide_handshake_12_1.lua lk_tr_handshake_12_1.lua lk_tr_handshake_12_2.lua lk_tr_handshake_12_3.lua lk_tr_handshake_12_4.lua lk_tr_handshake_12_6.lua lk_tr_handshake_12_12.lua
SIG16 += lk_wide_handshake_6_1.lua lk_wide_handshake_6_4.lua lk_tr_handshake_6_6.lua lk_tr_handshake_6_3.lua  lk_tr_handshake_6_2.lua lk_tr_handshake_6_1.lua
SIG16 += lk_wide_handshake_4_4.lua lk_wide_handshake_4_1.lua lk_tr_handshake_4_4.lua lk_tr_handshake_4_2.lua lk_tr_handshake_4_1.lua
SIG16 += sift_hw_4.lua sift_hw_1.lua sift_hw_4_1080p.lua sift_desc_hw.lua

SIG16_TODO := $(patsubst %.lua,$(BUILDDIR)/%.zu9vivado.launch,$(SIG16))
SIG16_TODO += $(patsubst %.lua,$(BUILDDIR)/%.verilator.launch,$(SIG16))
SIG16_TODO += $(patsubst %.lua,$(BUILDDIR)/%.v.launch,$(SIG16))
SIG16_TODO += $(patsubst %.lua,$(BUILDDIR)/%.zu9vivado.stats2020.launch,$(SIG16))

VERILOG := $(patsubst %.lua,$(BUILDDIR)/%.v.launch,$(SIG20))
VERILOG += $(patsubst %.lua,$(BUILDDIR)/%.v.launch,$(SIG16))

VERILATORSOC := $(patsubst %.lua,$(BUILDDIR)/%.verilatorSOCcorrect.launch,$(SIG20))
VERILATORSOC += $(patsubst %.lua,$(BUILDDIR)/%.v.launch,$(SIG20))

all: $(SIG20_TODO) $(SIG16_TODO)

sig16: $(SIG16_TODO)

sig20: $(SIG20_TODO)

sig20cpp: $(SIG20CPP_TODO)

verilog: $(VERILOG)

verilatorSOC: $(VERILATORSOC)

$(BUILDDIR)/%.v.launch: %.lua
	nc run -N $*.v -- make out/$*.v | grep JobId | grep -Eo "[0-9]+" > $@

$(BUILDDIR)/%.v.launch: out/%.lua
	nc run -N $*.v -- make out/$*.v | grep JobId | grep -Eo "[0-9]+" > $@

###########
$(BUILDDIR)/%.zu9vivadoSOC.launch: $(BUILDDIR)/%.v.launch
	nc run -N $*.zu9vivadoSOC.bit -d $*.v -- make out/$*.zu9vivadoSOC.bit | grep JobId | grep -Eo "[0-9]+" > $@

$(BUILDDIR)/%.verilatorSOC.launch: $(BUILDDIR)/%.v.launch
	nc run -N $*.verilatorSOC.raw -d $*.v -- make out/$*.verilatorSOC.raw | grep JobId | grep -Eo "[0-9]+" > $@

$(BUILDDIR)/%.verilatorSOCcorrect.launch: $(BUILDDIR)/%.v.launch
	nc run -N $*.verilatorSOC.correct.txt -d $*.v -- make out/$*.verilatorSOC.correct.txt | grep JobId | grep -Eo "[0-9]+" > $@

$(BUILDDIR)/%.zu9vivadoSOC.stats2020.launch: $(BUILDDIR)/%.verilatorSOC.launch $(BUILDDIR)/%.zu9vivadoSOC.launch
	nc run -N $*.zu9vivadoSOC.stats2020.txt -d $*.verilatorSOC.raw,$*.zu9vivadoSOC.bit -- make out/$*.zu9vivadoSOC.stats2020.txt | grep JobId | grep -Eo "[0-9]+" > $@

###########
$(BUILDDIR)/%.zu9vivado.launch: $(BUILDDIR)/%.v.launch
	nc run -N $*.zu9vivado.bit -d $*.v -- make out/$*.zu9vivado.bit | grep JobId | grep -Eo "[0-9]+" > $@

$(BUILDDIR)/%.verilator.launch: $(BUILDDIR)/%.v.launch
	nc run -N $*.verilator.raw -d $*.v -- make out/$*.verilator.raw | grep JobId | grep -Eo "[0-9]+" > $@

$(BUILDDIR)/%.zu9vivado.stats2020.launch: $(BUILDDIR)/%.zu9vivado.launch $(BUILDDIR)/%.verilator.launch
	nc run -N $*.zu9vivado.stats2020.txt -d $*.verilator.raw,$*.zu9vivado.bit -- make out/$*.zu9vivado.stats2020.txt | grep JobId | grep -Eo "[0-9]+" > $@


############
# C++
out/soc_convgenTaps_8_1_autofifo.lua out/soc_convgenTaps_8_2_autofifo.lua out/soc_convgenTaps_8_4_autofifo.lua  out/soc_convgenTaps_8_8_autofifo.lua out/soc_convgenTaps_8_16_autofifo.lua out/soc_convgenTaps_8_32_autofifo.lua out/soc_convgenTaps_8_64_autofifo.lua out/soc_convgenTaps_8_1.lua out/soc_convgenTaps_8_2.lua out/soc_convgenTaps_8_4.lua  out/soc_convgenTaps_8_8.lua out/soc_convgenTaps_8_16.lua out/soc_convgenTaps_8_32.lua out/soc_convgenTaps_8_64.lua: soc_convgenTaps.cpp
	make out/soc_convgenTaps
	./out/soc_convgenTaps

out/soc_stereo_full_64_64_autofifo.lua out/soc_stereo_full_64_32_autofifo.lua out/soc_stereo_full_64_16_autofifo.lua out/soc_stereo_full_64_8_autofifo.lua out/soc_stereo_full_64_4_autofifo.lua out/soc_stereo_full_64_64.lua out/soc_stereo_full_64_32.lua out/soc_stereo_full_64_16.lua out/soc_stereo_full_64_8.lua out/soc_stereo_full_64_4.lua: soc_stereo.cpp
	make out/soc_stereo
	./out/soc_stereo

out/soc_lk_12_24_autofifo.lua out/soc_lk_12_12_autofifo.lua out/soc_lk_12_6_autofifo.lua out/soc_lk_12_4_autofifo.lua out/soc_lk_12_3_autofifo.lua out/soc_lk_12_2_autofifo.lua out/soc_lk_12_1_autofifo.lua out/soc_lk_12_24.lua out/soc_lk_12_12.lua out/soc_lk_12_6.lua out/soc_lk_12_4.lua out/soc_lk_12_3.lua out/soc_lk_12_2.lua out/soc_lk_12_1.lua: soc_lk.cpp
	make out/soc_lk
	./out/soc_lk

out/soc_sift_4_64_1080p.lua out/soc_sift_4_128_1080p.lua out/soc_sift_4_256_1080p.lua out/soc_sift_4_64_1080p_autofifo.lua out/soc_sift_4_128_1080p_autofifo.lua out/soc_sift_4_256_1080p_autofifo.lua: soc_sift.cpp
	make out/soc_sift
	./out/soc_sift
