BUILDDIR ?= out

SIG20 := soc_lk_12_12.lua soc_lk_12_6.lua soc_lk_12_4.lua soc_lk_12_3.lua soc_lk_12_2.lua soc_lk_12_1.lua soc_lk_12_24.lua soc_lk_12_48.lua soc_lk_6_6.lua soc_lk_4_4.lua soc_lk_4_2.lua soc_lk_4_1.lua soc_lk_4_8.lua
SIG20 += soc_convgenTaps_8_1.lua soc_convgenTaps_8_2.lua soc_convgenTaps_8_4.lua  soc_convgenTaps_8_8.lua soc_convgenTaps_8_16.lua soc_convgenTaps_8_32.lua
SIG20 += soc_stereo_tiny_4_4.lua soc_stereo_tiny_4_1.lua soc_stereo_tiny_4_2.lua soc_stereo_tiny_4_8.lua soc_stereo_full_64_64.lua soc_stereo_full_64_32.lua soc_stereo_full_64_16.lua soc_stereo_full_64_8.lua soc_stereo_full_64_4.lua

SIG20_TODO := $(patsubst %.lua,$(BUILDDIR)/%.zu9vivadoSOC.launch,$(SIG20))
SIG20_TODO += $(patsubst %.lua,$(BUILDDIR)/%.verilatorSOC.launch,$(SIG20))
SIG20_TODO += $(patsubst %.lua,$(BUILDDIR)/%.v.launch,$(SIG20))
SIG20_TODO += $(patsubst %.lua,$(BUILDDIR)/%.v.launch,$(SIG20))
SIG20_TODO += $(patsubst %.lua,$(BUILDDIR)/%.zu9vivadoSOC.stats2020.launch,$(SIG20))

SIG16 := convpadcrop_wide_handshake_8_8_1080p.lua convpadcrop_wide_handshake_8_4_1080p.lua convpadcrop_wide_handshake_8_2_1080p.lua conv_tr_handshake_8_1_1080p.lua conv_tr_handshake_8_2_1080p.lua conv_tr_handshake_8_4_1080p.lua conv_tr_handshake_8_8_1080p.lua
SIG16 += stereo_wide_handshake_full.lua stereo_tr_full_4.lua stereo_tr_full_8.lua stereo_tr_full_16.lua stereo_wide_handshake_tiny.lua stereo_tr_tiny_1.lua stereo_tr_tiny_2.lua stereo_tr_tiny_4.lua
SIG16 += lk_wide_handshake_12_1.lua lk_tr_handshake_12_1.lua lk_tr_handshake_12_2.lua lk_tr_handshake_12_3.lua lk_tr_handshake_12_4.lua lk_tr_handshake_12_6.lua lk_tr_handshake_12_12.lua sift_hw_1080p.lua
SIG16 += lk_wide_handshake_4_4.lua lk_wide_handshake_4_1.lua lk_tr_handshake_4_4.lua
SIG16 += sift_hw.lua sift_hw_1080p.lua sift_desc_hw.lua

SIG16_TODO := $(patsubst %.lua,$(BUILDDIR)/%.zu9vivado.launch,$(SIG16))
SIG16_TODO += $(patsubst %.lua,$(BUILDDIR)/%.verilator.launch,$(SIG16))
SIG16_TODO += $(patsubst %.lua,$(BUILDDIR)/%.v.launch,$(SIG16))
SIG16_TODO += $(patsubst %.lua,$(BUILDDIR)/%.zu9vivado.stats2020.launch,$(SIG16))

VERILOG := $(patsubst %.lua,$(BUILDDIR)/%.v.launch,$(SIG20))
VERILOG += $(patsubst %.lua,$(BUILDDIR)/%.v.launch,$(SIG16))

all: $(SIG20_TODO) $(SIG16_TODO)

verilog: $(VERILOG)

$(BUILDDIR)/%.v.launch: %.lua
	nc run -N $*.v -- make out/$*.v | grep JobId | grep -Eo "[0-9]+" > $@

###########
$(BUILDDIR)/%.zu9vivadoSOC.launch: $(BUILDDIR)/%.v.launch
	nc run -N $*.zu9vivadoSOC.bit -d $*.v -- make out/$*.zu9vivadoSOC.bit | grep JobId | grep -Eo "[0-9]+" > $@

$(BUILDDIR)/%.verilatorSOC.launch: $(BUILDDIR)/%.v.launch
	nc run -N $*.verilatorSOC.raw -d $*.v -- make out/$*.verilatorSOC.raw | grep JobId | grep -Eo "[0-9]+" > $@

$(BUILDDIR)/%.zu9vivadoSOC.stats2020.launch: $(BUILDDIR)/%.verilatorSOC.launch $(BUILDDIR)/%.zu9vivadoSOC.launch
	nc run -N $*.zu9vivadoSOC.stats2020.txt -d $*.verilatorSOC.raw,$*.zu9vivadoSOC.bit -- make out/$*.zu9vivadoSOC.stats2020.txt | grep JobId | grep -Eo "[0-9]+" > $@

###########
$(BUILDDIR)/%.zu9vivado.launch: $(BUILDDIR)/%.v.launch
	nc run -N $*.zu9vivado.bit -d $*.v -- make out/$*.zu9vivado.bit | grep JobId | grep -Eo "[0-9]+" > $@

$(BUILDDIR)/%.verilator.launch: $(BUILDDIR)/%.v.launch
	nc run -N $*.verilator.raw -d $*.v -- make out/$*.verilator.raw | grep JobId | grep -Eo "[0-9]+" > $@

$(BUILDDIR)/%.zu9vivado.stats2020.launch: $(BUILDDIR)/%.zu9vivado.launch $(BUILDDIR)/%.verilator.launch
	nc run -N $*.zu9vivado.stats2020.txt -d $*.verilator.raw,$*.zu9vivado.bit -- make out/$*.zu9vivado.stats2020.txt | grep JobId | grep -Eo "[0-9]+" > $@