#!/bin/bash -x

VERILOG_FILE=$1
METADATA_FILE=$2
BUILDDIR=$3
OUTFILE=$4

mkdir -p $BUILDDIR
cd $BUILDDIR
echo "read_verilog $VERILOG_FILE" > system.tcl
echo "read_xdc ../../../platform/zynq10vivado/zybo.xdc" >> system.tcl
echo "read_xdc ../../../platform/vivado/ps7_constraints.xdc" >> system.tcl
echo "synth_design -top stage -part xc7z010clg400-1" >> system.tcl
echo "opt_design" >> system.tcl
echo "place_design" >> system.tcl
echo "phys_opt_design" >> system.tcl
echo "route_design" >> system.tcl
echo "write_bitstream system.bit" >> system.tcl
echo "report_timing" >> system.tcl
echo "report_timing_summary" >> system.tcl
vivado -mode batch -source 'system.tcl' -nojournal -log 'vivado.log' > /dev/null
bootgen -image ../../../platform/axi/boot.bif -w -process_bitstream bin
cp system.bit.bin $OUTFILE
                                          
