language: c

before_install:
  - sudo apt-get -qq update

  # luajit
  - sudo apt-get install luajit

  # z3
  - if [[ $TARGET = "verilatorSOC" ]] || [[ $TARGET = "terra" ]]; then wget https://github.com/Z3Prover/z3/releases/download/z3-4.7.1/z3-4.7.1-x64-ubuntu-14.04.zip; fi
  - if [[ $TARGET = "verilatorSOC" ]] || [[ $TARGET = "terra" ]]; then unzip z3-4.7.1-x64-ubuntu-14.04.zip; fi
  - if [[ $TARGET = "verilatorSOC" ]] || [[ $TARGET = "terra" ]]; then export PATH=$PATH:$PWD/z3-4.7.1-x64-ubuntu-14.04/bin; fi
  - if [[ $TARGET = "verilatorSOC" ]] || [[ $TARGET = "terra" ]]; then z3 --version; fi
    
  # verilator
  - if [[ $TARGET = "verilator" ]] || [[ $TARGET = "verilatorSOC" ]] || [[ $TARGET = "unit" ]]; then sudo apt-get install verilator; fi
  - if [[ $TARGET = "verilator" ]] || [[ $TARGET = "verilatorSOC" ]] || [[ $TARGET = "unit" ]]; then export PKG_CONFIG_PATH=/home/travis/build/jameshegarty/rigel/platform/verilator; fi

  # bjump requires more recent verilator
  - if [[ $TARGET = "bjump" ]]; then wget https://www.veripool.org/ftp/verilator-4.012.tgz; tar xvzf verilator*.t*gz;cd verilator*;./configure;make -j2;sudo make install; cd ..; fi
  
  #terra
  - if [[ $TARGET = "terra" ]] || [[ $TARGET = "unit" ]]; then wget https://github.com/zdevito/terra/releases/download/release-2016-03-25/terra-Linux-x86_64-332a506.zip; fi
  - if [[ $TARGET = "terra" ]] || [[ $TARGET = "unit" ]]; then unzip terra-Linux-x86_64-332a506.zip; fi
  - if [[ $TARGET = "terra" ]] || [[ $TARGET = "unit" ]]; then sudo ln -s /home/travis/build/jameshegarty/rigel/terra-Linux-x86_64-332a506/bin/terra /usr/bin/terra; fi

  # this installs correct version of glibc for terra binary
  - if [[ $TARGET = "terra" ]] || [[ $TARGET = "unit" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [[ $TARGET = "terra" ]] || [[ $TARGET = "unit" ]]; then sudo apt-get -y update; fi
  - if [[ $TARGET = "terra" ]] || [[ $TARGET = "unit" ]]; then sudo apt-get -y install libstdc++6-4.7-dev; fi

#for coveralls
  - if [[ $TARGET = "unit" ]] || [[ $TARGET = "coverage" ]]; then sudo apt-get install luarocks; fi
  - if [[ $TARGET = "unit" ]] || [[ $TARGET = "coverage" ]]; then sudo luarocks install luacov-coveralls; fi
  - if [[ $TARGET = "unit" ]] || [[ $TARGET = "coverage" ]]; then eval `luarocks path --bin`; fi

script:
  # early out on errors
  - set -e
  - if [[ $TARGET = "unit" ]]; then export LUA="../rigelLuajit -lluacov"; fi
  - if [[ $TARGET = "unit" ]]; then cd unittests;  make;  else cd examples;  make -j2 $TARGET; fi
  - if [[ $TARGET = "verilog" ]]; then make -j2 wrapper; fi
  # check that make actually 100% completed, just to be really sure (?)
  - pwd
  - echo out/${TARGET}_done.txt
  - if [[ $TARGET != "unit" ]]; then test -e out/${TARGET}_done.txt || exit; fi
  - if [[ $TARGET = "unit" ]]; then luacov-coveralls -v; fi
  
env:
  - TARGET=verilog
  - TARGET=verilator
  - TARGET=verilatorSOC
  - TARGET=terra
  - TARGET=bjump
  - TARGET=unit
  - TARGET=coverage
#  - TARGET=axiverilog
