#!/bin/bash

set -x

BITFILE=$1
BITFILE_BASE=$(basename $1)
METAFILE=$2
OUTFILE=$3
OUTPATH=$4

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

LUA=$DIR/../../rigelLuajit

CYCLES=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE cycles)
COOLDOWN=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE cooldown)
MEMSTART=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE memoryStart)
MEMEND=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE memoryEnd)
INPUTS=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE __INPUTS)
OUTPUTS=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE __OUTPUTS)
REGISTERS=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE __REGISTERS)
REGISTERSOUT=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE __REGISTERSOUT)

#VERBOSE=--verbose

echo "* run"
$BITFILE $CYCLES $COOLDOWN $MEMSTART $MEMEND $VERBOSE --inputs $INPUTS --registers $REGISTERS --outputs $OUTPUTS --registersOut $REGISTERSOUT
