#!/bin/bash

set -x

BITFILE=$1
BITFILE_BASE=$(basename $1)
METAFILE=$2
OUTFILE=$3
OUTPATH=$4

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

LUA=$DIR/../../rigelLuajit

CYCLES=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE cycles)
MEMSTART=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE memoryStart)
MEMEND=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE memoryEnd)
INPUTS=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE __INPUTS)
OUTPUTS=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE __OUTPUTS)

#VERBOSE=--verbose

$BITFILE $CYCLES $MEMSTART $MEMEND $VERBOSE --inputs $INPUTS --outputs $OUTPUTS
