#!/bin/bash -x

VERILOG_FILE=$1
METADATA_FILE=$2
BUILDDIR=$3
OUTFILE=$4
NAME=$5

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

TCLFILE=$NAME.tcl

mkdir -p $BUILDDIR
$DIR/../../rigelLuajit $DIR/../../misc/extractMetadata.lua $METADATA_FILE __XDC > $BUILDDIR/zu9.xdc
$DIR/../../rigelLuajit $DIR/../../platform/axi/wrapper.lua $VERILOG_FILE $METADATA_FILE $VERILOG_FILE.mpsocwrapper.sv $DIR/../../platform/ mpsoc
cd $BUILDDIR
echo "read_verilog $VERILOG_FILE $VERILOG_FILE.mpsocwrapper.sv" > $TCLFILE
echo "synth_design -top MPSOC_Top -part xczu9eg-ffvb1156-2-e" >> $TCLFILE
echo "read_xdc zu9.xdc" >> $TCLFILE
echo "opt_design" >> $TCLFILE
echo "place_design" >> $TCLFILE
echo "phys_opt_design" >> $TCLFILE
echo "route_design" >> $TCLFILE
echo "write_checkpoint -force final.dcp" >> $TCLFILE
echo "write_bitstream -force system.bit" >> $TCLFILE
echo "report_timing" >> $TCLFILE
echo "report_timing_summary" >> $TCLFILE
echo "report_utilization -hierarchical -file utilization_h.txt" >> $TCLFILE
echo "report_utilization -file utilization.txt" >> $TCLFILE
vivado -source $TCLFILE -mode batch -nojournal -log 'vivado.log' > /dev/null
bootgen -image $DIR/../axi/boot.bif -arch zynqmp -process_bitstream bin
cp $BUILDDIR/system.bit.bin $OUTFILE
                                          
