#!/bin/bash -x
# -x shows all commands

ZYNQ_WRITE_PATH=/home/root
ZYNQ_ADDR=${4:-192.168.1.151} # arg 4, or default 192.168.1.151

ZYNQ_BIN_FILE_PATH=/lib/firmware/
ZYNQ_FIRMWARE_PATH=/sys/class/fpga_manager/fpga0/firmware

BITFILE=$1
BITFILE_BASE=$(basename $1)
METAFILE=$2
OUTFILE=$3
#OUTPATH=$4

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

LUA=$DIR/../../rigelLuajit

#out/%.axi.raw: out/%.axi.bit out/%.hz.txt out/%.axi.metadata.lua
IMGPATH=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE inputImage)
IMGFILE=$(basename $IMGPATH)
INW=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE inputWidth)
INH=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE inputHeight)
BPP_IN=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE inputBitsPerPixel)
BPP_OUT=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE outputBitsPerPixel)
OUTW=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE outputWidth)
OUTH=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE outputHeight)
TAPVALUE=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE tapValue)
###### SET THE CLOCK	
#HZ=$(cat $OUTPATH.hz.txt)
#lockfile /tmp/zynq10lock
# (* second time around we can't write to fclk_export, so surpress error)
#sshpass -p 'root' ssh root@$ZYNQ_ADDR "if [[ ! -a /sys/devices/amba.0/f8007000.ps7-dev-cfg/fclk/fclk0 ]]; then echo 'fclk0' > /sys/devices/amba.0/f8007000.ps7-dev-cfg/fclk_export; fi"
#	sshpass -p 'root' ssh root@$ZYNQ_ADDR "echo '$($@_HZ)' > /sys/class/fclk/fclk0/set_rate"
#	sshpass -p 'root' ssh root@$ZYNQ_ADDR "cat /sys/class/fclk/fclk0/set_rate" > out/$*.realhz.txt
###### CLOCK STUFF END

sshpass -p 'root' scp $DIR/../mpsoc/processimage_mpsoc $BITFILE $IMGPATH root@$ZYNQ_ADDR:$ZYNQ_WRITE_PATH
sshpass -p 'root' ssh root@$ZYNQ_ADDR "mv $ZYNQ_WRITE_PATH/$BITFILE_BASE $ZYNQ_BIN_FILE_PATH"
sshpass -p 'root' ssh root@$ZYNQ_ADDR "echo $BITFILE_BASE > $ZYNQ_FIRMWARE_PATH"
sshpass -p 'root' ssh root@$ZYNQ_ADDR "$ZYNQ_WRITE_PATH/processimage_mpsoc A0000000 30008000 $ZYNQ_WRITE_PATH/$IMGFILE $ZYNQ_WRITE_PATH/out.raw $INW $INH $BPP_IN $OUTW $OUTH $BPP_OUT $TAPVALUE"
sshpass -p 'root' scp root@$ZYNQ_ADDR:$ZYNQ_WRITE_PATH/out.raw $OUTFILE
sshpass -p 'root' ssh root@$ZYNQ_ADDR "rm $ZYNQ_WRITE_PATH/processimage_mpsoc $ZYNQ_WRITE_PATH/$IMGFILE $ZYNQ_WRITE_PATH/out.raw $ZYNQ_BIN_FILE_PATH/$BITFILE_BASE"
#rm -f /tmp/zynq10lock
#	$(TERRA) ../misc/extractCycles.t out/$*.axi.raw > out/$*.axi.cycles.txt
#	# keep copy for future reference
#	cp out/$*.axi.cycles.txt out/build_$*
