#!/bin/bash

# print all commands
# set -x

# early exit on errors (so that verilator warnings are errors)
set -e

# usage: verilogFile metadataFile buildDir outputFile
# buildDir is a directory where intermediates can be stored (WITHOUT trailing slash)

VERILATOR_INCLUDE_PKGCFG=$(exec pkg-config --variable=includedir verilator)
VERILATOR_CFLAGS_PKGCFG=$(exec pkg-config --cflags verilator)

VERILATOR_INCLUDE="${VERILATOR_INCLUDE:-$VERILATOR_INCLUDE_PKGCFG}"
VERILATOR_CFLAGS="${VERILATOR_CFLAGS:-$VERILATOR_CFLAGS_PKGCFG}"

VERILOG_FILE=$1
METADATA_FILE=$2
BUILDDIR=$3
OUTFILE=$4

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

TOP=$(exec luajit $DIR/../../misc/extractMetadata.lua $METADATA_FILE topModule)
HARNESS=$(exec luajit $DIR/../../misc/extractMetadata.lua $METADATA_FILE harness)
INBPP=$(exec luajit $DIR/../../misc/extractMetadata.lua $METADATA_FILE inputBitsPerPixel)

# HACK
RAMBITS=$(exec luajit $DIR/../../misc/extractMetadata.lua $METADATA_FILE ramBits)
RAMFILE=$(exec luajit $DIR/../../misc/extractMetadata.lua $METADATA_FILE ramFile)

TAPBITS=$(exec luajit $DIR/../../misc/extractMetadata.lua $METADATA_FILE tapBits)

#-Wno-UNOPTFLAT surpresses circular loop errors... we should probably work to not have to enable this
verilator -Wno-UNOPTFLAT -cc -Mdir $BUILDDIR $VERILOG_FILE $DIR/RAM128X1D.v $DIR/RAMB16_S36_S36.v $DIR/RAMB16_S18_S18.v $DIR/RAMB16_S9_S9.v $DIR/RAMB16_RIGEL.v --top-module $TOP
make -C $BUILDDIR -f V$TOP.mk
g++ ${VERILATOR_CFLAGS} -I. -DHARNESS=$HARNESS -DINBPP=$INBPP -DRAMBITS=$RAMBITS -DRAMFILE="\"$RAMFILE\"" -DTAPBITS=$TAPBITS -DVERILATORCLASS="V${TOP}" -DVERILATORFILE="\"${BUILDDIR}/V${TOP}.h\"" ${VERILATOR_INCLUDE}/verilated.cpp $DIR/harness.cpp $BUILDDIR/V${TOP}__ALL.a -o $OUTFILE
