#!/bin/bash -x
# -x shows all commands

ZYNQ_WRITE_PATH=/home/root
ZYNQ_ETH=${ZYNQ_ETH:-enp10s0}    
ZYNQ_BIN_FILE_PATH=/lib/firmware/
ZYNQ_FIRMWARE_PATH=/sys/class/fpga_manager/fpga0/firmware

BITFILE=$1
BITFILE_BASE=$(basename $1)
METAFILE=$2
OUTFILE=$3
OUTPATH=$4

while [[ -z `ip -6 neigh show | grep $ZYNQ_ETH | cut -d " " -f1` ]]
do
    echo "Finding IP..."
    ping6 -c 5 -I enp10s0 FF02:0:0:0:0:0:0:1
    sleep 1
done

IPT=$(ip -6 neigh show | grep enp10s0 | cut -d " " -f1)
ZYNQ_ADDR=$IPT%$ZYNQ_ETH
echo $ZYNQ_ADDR

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

LUA=$DIR/../../rigelLuajit

MEMSTART=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE memoryStart)
MEMEND=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE memoryEnd)
INPUTS=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE __INPUTS_ZYNQ)
OUTPUTS=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE __OUTPUTS_ZYNQ)
REGISTERS=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE __REGISTERS)
REGISTERSOUT=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE __REGISTERSOUT)

INPUT_FILES_ON_HOST=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE __INPUT_HOST_FILES)
INPUT_FILES_ON_DEVICE=$($LUA $DIR/../../misc/extractMetadata.lua $METAFILE __INPUT_DEVICE_FILES)


###### SET THE CLOCK	
#HZ=$(cat $OUTPATH.hz.txt)
#lockfile /tmp/zynq10lock
# (* second time around we can't write to fclk_export, so surpress error)
#sshpass -p 'root' ssh root@$ZYNQ_ADDR "if [[ ! -a /sys/devices/amba.0/f8007000.ps7-dev-cfg/fclk/fclk0 ]]; then echo 'fclk0' > /sys/devices/amba.0/f8007000.ps7-dev-cfg/fclk_export; fi"
#	sshpass -p 'root' ssh root@$ZYNQ_ADDR "echo '$($@_HZ)' > /sys/class/fclk/fclk0/set_rate"
#	sshpass -p 'root' ssh root@$ZYNQ_ADDR "cat /sys/class/fclk/fclk0/set_rate" > out/$*.realhz.txt
###### CLOCK STUFF END

SSHOPT="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -6"

#ssh-keygen -f ~/.ssh/known_hosts -R $ZYNQ_ADDR
sshpass -p 'root' scp $SSHOPT $DIR/processimage_mpsoc_SOC $BITFILE $INPUT_FILES_ON_HOST root@\[$ZYNQ_ADDR\]:$ZYNQ_WRITE_PATH
sshpass -p 'root' ssh $SSHOPT root@$ZYNQ_ADDR "mv $ZYNQ_WRITE_PATH/$BITFILE_BASE $ZYNQ_BIN_FILE_PATH"
sshpass -p 'root' ssh $SSHOPT root@$ZYNQ_ADDR "echo $BITFILE_BASE > $ZYNQ_FIRMWARE_PATH"
sshpass -p 'root' ssh $SSHOPT root@$ZYNQ_ADDR "$ZYNQ_WRITE_PATH/processimage_mpsoc_SOC 0xA0000000 $MEMSTART $MEMEND --inputs $INPUTS --registers $REGISTERS --registersOut $REGISTERSOUT --outputs $OUTPUTS"
sshpass -p 'root' scp $SSHOPT root@\[$ZYNQ_ADDR\]:$ZYNQ_WRITE_PATH/out.raw $OUTFILE
sshpass -p 'root' scp $SSHOPT root@\[$ZYNQ_ADDR\]:$ZYNQ_WRITE_PATH/regout.lua $(echo $OUTPATH)zu9vivadoSOC.regout.lua
sshpass -p 'root' ssh $SSHOPT root@$ZYNQ_ADDR "rm $ZYNQ_WRITE_PATH/processimage_mpsoc_SOC $INPUT_FILES_ON_DEVICE $ZYNQ_WRITE_PATH/out.raw $ZYNQ_WRITE_PATH/regout.lua $ZYNQ_BIN_FILE_PATH/$BITFILE_BASE"

#rm -f /tmp/zynq10lock
#	$(TERRA) ../misc/extractCycles.t out/$*.axi.raw > out/$*.axi.cycles.txt
#	# keep copy for future reference
#	cp out/$*.axi.cycles.txt out/build_$*
