#!/bin/bash

VERILOG_FILE=$1
METADATA_FILE=$2
BUILDDIR=$3
OUTFILE=$4

mkdir -p $BUILDDIR
cd $BUILDDIR
echo "read_verilog $VERILOG_FILE" > system.tcl
echo "read_xdc ../../../platform/vivado/zedboard_master_XDC_RevC_D_v3.xdc" >> system.tcl
echo "read_xdc ../../../platform/vivado/ps7_constraints.xdc" >> system.tcl
echo "synth_design -top stage -part xc7z020clg484-1" >> system.tcl
echo "opt_design" >> system.tcl
echo "place_design" >> system.tcl
echo "phys_opt_design" >> system.tcl
echo "route_design" >> system.tcl
echo "write_bitstream -force system.bit" >> system.tcl
echo "report_timing" >> system.tcl
echo "report_timing_summary" >> system.tcl
vivado -mode batch -source 'system.tcl' -nojournal -log 'vivado.log' > /dev/null
cp system.bit $OUTFILE
                                          